language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install codacy-coverage

script:
  - nosetests --rednose -v --with-coverage --cover-erase --cover-xml --cover-package=app

after_success:
  - python-codacy-coverage -r coverage.xml

cache: pip

notifications:
  email: false